import React, { useMemo, useRef, useCallback } from 'react';
import {
  User,
  Download,
  Share2,
  Trophy,
  Clock,
  Gamepad2,
  BarChart3,
  Sparkles,
  Zap
} from 'lucide-react';
import { UserBehaviorProfile } from '../services/UserBehaviorProfile';
import { StatsAggregationService } from '../services/StatsAggregationService';
import GamingPersonaService from '../services/GamingPersonaService';
import './GamerIdentityCard.css';

const StatPill = ({ icon: Icon, label, value }) => (
  <div className="gamer-stat-pill">
    <Icon size={14} />
    <span className="gamer-stat-label">{label}</span>
    <span className="gamer-stat-value">{value}</span>
  </div>
);

const GamerIdentityCard = ({ library = [], className = '' }) => {
  const cardRef = useRef(null);

  const identity = useMemo(() => {
    if (!Array.isArray(library)) {
      return null;
    }

    const persona = GamingPersonaService.getPersona();
    const dashboard = StatsAggregationService.getDashboardData(library);
    const allTime = dashboard?.periods?.all;

    const topMoods = UserBehaviorProfile.getTopMoods(3);
    const topGenres = UserBehaviorProfile.getTopGenres(3);
    const peakHours = UserBehaviorProfile.getPeakPlayHours(1);

    return {
      label: persona?.primaryPersona?.label || 'Gamer in Progress',
      description: persona?.summaryRoast || persona?.primaryPersona?.roast || 'Building your gaming identity one session at a time.',
      tags: persona?.subTraits?.map((trait) => trait.label) || [],
      totalGames: library.length,
      totalHours: Math.round(allTime?.playtimeHours || 0),
      totalSessions: allTime?.sessions || 0,
      completedCount: allTime?.questUsage?.totalCompleted || 0,
      avgSession: allTime?.avgSessionMinutes || 0,
      topMoods,
      topGenres,
      peakWindow: peakHours[0]?.timeOfDay || 'Unknown',
      completionRate: allTime?.sessions > 0
        ? Math.round(((allTime?.questUsage?.totalCompleted || 0) / allTime.sessions) * 100)
        : 0
    };
  }, [library]);

  const handleExport = useCallback(() => {
    if (!cardRef.current || !identity) return;

    try {
      const canvas = document.createElement('canvas');
      const ctx = canvas.getContext('2d');
      const width = 800;
      const height = 480;
      canvas.width = width * 2;
      canvas.height = height * 2;
      ctx.scale(2, 2);

      // Background gradient based on persona
      const gradient = ctx.createLinearGradient(0, 0, width, height);
      gradient.addColorStop(0, '#0f172a');
      gradient.addColorStop(1, '#1e293b');
      ctx.fillStyle = gradient;
      ctx.fillRect(0, 0, width, height);

      // Accent bar
      ctx.fillStyle = '#3dd9ff';
      ctx.fillRect(0, 0, width, 6);

      // Title
      ctx.fillStyle = '#f1f5f9';
      ctx.font = 'bold 28px sans-serif';
      ctx.fillText('GamePilot Identity', 32, 52);

      // Persona label
      ctx.fillStyle = '#3dd9ff';
      ctx.font = 'bold 36px sans-serif';
      ctx.fillText(identity.label, 32, 110);

      // Description
      ctx.fillStyle = '#94a3b8';
      ctx.font = '18px sans-serif';
      const words = identity.description.split(' ');
      let line = '';
      let y = 148;
      for (const word of words) {
        const test = line + word + ' ';
        if (ctx.measureText(test).width > 520 && line !== '') {
          ctx.fillText(line, 32, y);
          line = word + ' ';
          y += 26;
        } else {
          line = test;
        }
      }
      ctx.fillText(line, 32, y);

      // Tags
      let tagX = 32;
      const tagY = y + 40;
      ctx.font = '14px sans-serif';
      identity.tags.slice(0, 4).forEach((tag) => {
        const textWidth = ctx.measureText(tag).width + 20;
        ctx.fillStyle = 'rgba(61, 217, 255, 0.15)';
        ctx.beginPath();
        ctx.roundRect(tagX, tagY - 18, textWidth, 28, 6);
        ctx.fill();
        ctx.fillStyle = '#3dd9ff';
        ctx.fillText(tag, tagX + 10, tagY);
        tagX += textWidth + 10;
      });

      // Stats grid
      const stats = [
        { label: 'Games', value: String(identity.totalGames) },
        { label: 'Hours', value: String(identity.totalHours) },
        { label: 'Sessions', value: String(identity.totalSessions) },
        { label: 'Avg Session', value: `${identity.avgSession}m` }
      ];

      let statX = 32;
      const statY = tagY + 60;
      stats.forEach((stat) => {
        ctx.fillStyle = '#64748b';
        ctx.font = '12px sans-serif';
        ctx.fillText(stat.label.toUpperCase(), statX, statY);
        ctx.fillStyle = '#f1f5f9';
        ctx.font = 'bold 24px sans-serif';
        ctx.fillText(stat.value, statX, statY + 28);
        statX += 140;
      });

      // Footer
      ctx.fillStyle = '#475569';
      ctx.font = '12px sans-serif';
      ctx.fillText('Generated by GamePilot — Your Gaming Librarian', 32, height - 20);

      // Download
      const link = document.createElement('a');
      link.download = `gamepilot-identity-${Date.now()}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
    } catch (e) {
      console.warn('GamerIdentityCard export failed:', e);
    }
  }, [identity]);

  const handleShare = useCallback(() => {
    if (!identity) return;
    const text = `My GamePilot Identity: ${identity.label}\n${identity.totalGames} games · ${identity.totalHours} hours · ${identity.totalSessions} sessions\n#GamePilot`;
    if (navigator.clipboard) {
      navigator.clipboard.writeText(text).catch(() => {});
    }
  }, [identity]);

  if (!identity) {
    return (
      <div className={`gamer-identity-card empty ${className}`}>
        <User size={32} />
        <p>Play more games to generate your gamer identity card.</p>
      </div>
    );
  }

  return (
    <div className={`gamer-identity-card ${className}`} ref={cardRef}>
      <div className="gamer-card-header">
        <div className="gamer-card-title">
          <Sparkles size={18} />
          <span>Gamer Identity</span>
        </div>
        <div className="gamer-card-actions">
          <button type="button" className="gamer-card-btn" onClick={handleExport} title="Export as image">
            <Download size={16} />
          </button>
          <button type="button" className="gamer-card-btn" onClick={handleShare} title="Copy summary">
            <Share2 size={16} />
          </button>
        </div>
      </div>

      <div className="gamer-card-identity">
        <div className="gamer-avatar">
          <User size={32} />
        </div>
        <div className="gamer-identity-body">
          <h4 className="gamer-identity-label">{identity.label}</h4>
          <p className="gamer-identity-desc">{identity.description}</p>
          <div className="gamer-identity-tags">
            {identity.tags.slice(0, 4).map((tag) => (
              <span key={tag} className="gamer-tag">{tag}</span>
            ))}
          </div>
        </div>
      </div>

      <div className="gamer-card-stats">
        <StatPill icon={Gamepad2} label="Games" value={identity.totalGames} />
        <StatPill icon={Clock} label="Hours" value={identity.totalHours} />
        <StatPill icon={Zap} label="Sessions" value={identity.totalSessions} />
        <StatPill icon={BarChart3} label="Avg" value={`${identity.avgSession}m`} />
        {identity.completedCount > 0 && (
          <StatPill icon={Trophy} label="Completed" value={identity.completedCount} />
        )}
      </div>

      <div className="gamer-card-footer">
        <span>Peak: {identity.peakWindow}</span>
        {identity.topGenres.length > 0 && (
          <span>Top Genre: {identity.topGenres[0].genre}</span>
        )}
      </div>
    </div>
  );
};

export default GamerIdentityCard;
